In [ ]:
 Inputs: 
    Name, Generation, Type
Outputs:
    Name, Generation, Type, Strength, Region, abilities
Algorith: 
    Import pandas
    Get data
    Input Name, Generation, Type
    Sort the database
    Filter out data using the input of the user
    Print out the pokemons attributes

In [2]:
import pandas as pd

In [3]:
mydata = pd.read_csv('pokemon.csv')
mydata.sample(3)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
592,"['Water Absorb', 'Cursed Body', 'Damp']",0.5,2.0,1.0,2.0,1.0,0.00,0.5,1.0,2.0,...,50.0,593,85,105,60,water,ghost,135.0,5,0
543,"['Poison Point', 'Swarm', 'Speed Boost']",0.5,1.0,1.0,1.0,0.5,0.25,2.0,2.0,1.0,...,50.0,544,40,79,47,bug,poison,58.5,5,0
146,"['Shed Skin', 'Marvel Scale']",1.0,1.0,2.0,0.5,2.0,1.00,0.5,1.0,1.0,...,50.0,147,50,50,50,dragon,NaN,3.3,1,0

In [34]:
pokedex_number = pd.Series(mydata['pokedex_number'])
names = pd.Series(mydata['name'])
generation = pd.Series(mydata['generation'])
types = pd.Series(mydata['type1'])
classfication = pd.Series(mydata['classfication'])
abilities = pd.Series(mydata['abilities'])
height = pd.Series(mydata['height_m'])
weight = pd.Series(mydata['weight_kg'])
hp = pd.Series(mydata['hp'])
speed = pd.Series(mydata['speed'])
attack= pd.Series(mydata['attack'])
defense = pd.Series(mydata['defense'])
series_dict = { 'Pokedex Number' : pokedex_number, 'Name':  names, 'Generation': generation, 'Types' : types, 'Classfication' : classfication, 'Abilities' : abilities, 'Height_m' : height, 'Weight_kg' : weight, 'Hp' : hp, 'Speed' : speed, 'sp_Attack' : attack, 'sp_Defense' : defense }
pokemons = pd.DataFrame( series_dict )
pokemons.sample(3)

,Pokedex Number,Name,Generation,Types,Classfication,Abilities,Height_m,Weight_kg,Hp,Speed,sp_Attack,sp_Defense
648,649,Genesect,5,bug,Paleozoic Pokémon,['Download'],1.5,82.5,71,99,120,95
180,181,Ampharos,2,electric,Light Pokémon,"['Static', 'Plus']",1.4,61.5,90,45,95,105
628,629,Vullaby,5,dark,Diapered Pokémon,"['Big Pecks', 'Overcoat', 'Weak Armor']",0.5,9.0,70,60,55,75

In [35]:
pokemons.head(2)

,Pokedex Number,Name,Generation,Types,Classfication,Abilities,Height_m,Weight_kg,Hp,Speed,sp_Attack,sp_Defense
0,1,Bulbasaur,1,grass,Seed Pokémon,"['Overgrow', 'Chlorophyll']",0.7,6.9,45,45,49,49
1,2,Ivysaur,1,grass,Seed Pokémon,"['Overgrow', 'Chlorophyll']",1.0,13.0,60,60,62,63

In [36]:
pokemons[pokemons['Types'] == 'grass' ].head(2)

,Pokedex Number,Name,Generation,Types,Classfication,Abilities,Height_m,Weight_kg,Hp,Speed,sp_Attack,sp_Defense
0,1,Bulbasaur,1,grass,Seed Pokémon,"['Overgrow', 'Chlorophyll']",0.7,6.9,45,45,49,49
1,2,Ivysaur,1,grass,Seed Pokémon,"['Overgrow', 'Chlorophyll']",1.0,13.0,60,60,62,63

In [37]:
pokemons[pokemons['Types'] == 'fire' ].tail(2)

,Pokedex Number,Name,Generation,Types,Classfication,Abilities,Height_m,Weight_kg,Hp,Speed,sp_Attack,sp_Defense
740,741,Oricorio,7,fire,Dancing Pokémon,['Dancer'],0.6,3.4,75,93,70,70
775,776,Turtonator,7,fire,Blast Turtle Pokémon,['Shell Armor'],2.0,212.0,60,36,78,135

In [38]:
pokemons[pokemons['Generation'] == 3 ].tail(2)

,Pokedex Number,Name,Generation,Types,Classfication,Abilities,Height_m,Weight_kg,Hp,Speed,sp_Attack,sp_Defense
384,385,Jirachi,3,steel,Wish Pokémon,['Serene Grace'],0.3,1.1,100,100,100,100
385,386,Deoxys,3,psychic,DNA Pokémon,['Pressure'],1.7,60.8,50,180,95,90

In [39]:
pokemons[(pokemons.Generation == 3) ]

,Pokedex Number,Name,Generation,Types,Classfication,Abilities,Height_m,Weight_kg,Hp,Speed,sp_Attack,sp_Defense
251,252,Treecko,3,grass,Wood Gecko Pokémon,"['Overgrow', 'Unburden']",0.5,5.0,40,70,45,35
252,253,Grovyle,3,grass,Wood Gecko Pokémon,"['Overgrow', 'Unburden']",0.9,21.6,50,95,65,45
253,254,Sceptile,3,grass,Forest Pokémon,"['Overgrow', 'Unburden']",1.7,52.2,70,145,110,75
254,255,Torchic,3,fire,Chick Pokémon,"['Blaze', 'Speed Boost']",0.4,2.5,45,45,60,40
255,256,Combusken,3,fire,Young Fowl Pokémon,"['Blaze', 'Speed Boost']",0.9,19.5,60,55,85,60
256,257,Blaziken,3,fire,Blaze Pokémon,"['Blaze', 'Speed Boost']",1.9,52.0,80,100,160,80
257,258,Mudkip,3,water,Mud Fish Pokémon,"['Torrent', 'Damp']",0.4,7.6,50,40,70,50
258,259,Marshtomp,3,water,Mud Fish Pokémon,"['Torrent', 'Damp']",0.7,28.0,70,50,85,70
259,260,Swampert,3,water,Mud Fish Pokémon,"['Torrent', 'Damp']",1.5,81.9,100,70,150,110
260,261,Poochyena,3,dark,Bite Pokémon,"['Run Away', 'Quick Feet', 'Rattled']",0.5,13.6,35,35,55,35
261,262,Mightyena,3,dark,Bite Pokémon,"['Intimidate', 'Quick Feet', 'Moxie']",1.0,37.0,70,70,90,70
262,263,Zigzagoon,3,normal,Tiny Racoon Pokémon,"['Pickup', 'Gluttony', 'Quick Feet']",0.4,17.5,38,60,30,41
263,264,Linoone,3,normal,Rush Pokémon,"['Pickup', 'Gluttony', 'Quick Feet']",0.5,32.5,78,100,70,61
264,265,Wurmple,3,bug,Worm Pokémon,"['Shield Dust', 'Run Away']",0.3,3.6,45,20,45,35
265,266,Silcoon,3,bug,Cocoon Pokémon,['Shed Skin'],0.6,10.0,50,15,35,55
266,267,Beautifly,3,bug,Butterfly Pokémon,"['Swarm', 'Rivalry']",1.0,28.4,60,65,70,50
267,268,Cascoon,3,bug,Cocoon Pokémon,['Shed Skin'],0.7,11.5,50,15,35,55
268,269,Dustox,3,bug,Poison Moth Pokémon,"['Shield Dust', 'Compoundeyes']",1.2,31.6,60,65,50,70
269,270,Lotad,3,water,Water Weed Pokémon,"['Swift Swim', 'Rain Dish', 'Own Tempo']",0.5,2.6,40,30,30,30
270,271,Lombre,3,water,Jolly Pokémon,"['Swift Swim', 'Rain Dish', 'Own Tempo']",1.2,32.5,60,50,50,50
271,272,Ludicolo,3,water,Carefree Pokémon,"['Swift Swim', 'Rain Dish', 'Own Tempo']",1.5,55.0,80,70,70,70
272,273,Seedot,3,grass,Acorn Pokémon,"['Chlorophyll', 'Early Bird', 'Pickpocket']",0.5,4.0,40,30,40,50
273,274,Nuzleaf,3,grass,Wily Pokémon,"['Chlorophyll', 'Early Bird', 'Pickpocket']",1.0,28.0,70,60,70,40
274,275,Shiftry,3,grass,Wickid Pokémon,"['Chlorophyll', 'Early Bird', 'Pickpocket']",1.3,59.6,90,80,100,60
275,276,Taillow,3,normal,TinySwallow Pokémon,"['Guts', 'Scrappy']",0.3,2.3,40,85,55,30
276,277,Swellow,3,normal,Swallow Pokémon,"['Guts', 'Scrappy']",0.7,19.8,60,125,85,60
277,278,Wingull,3,water,Seagull Pokémon,"['Keen Eye', 'Hydration', 'Rain Dish']",0.6,9.5,40,85,30,30
278,279,Pelipper,3,water,Water Bird Pokémon,"['Keen Eye', 'Drizzle', 'Rain Dish']",1.2,28.0,60,65,50,100
279,280,Ralts,3,psychic,Feeling Pokémon,"['Synchronize', 'Trace', 'Telepathy']",0.4,6.6,28,40,25,25
280,281,Kirlia,3,psychic,Emotion Pokémon,"['Synchronize', 'Trace', 'Telepathy']",0.8,20.2,38,50,35,35
...,...,...,...,...,...,...,...,...,...,...,...,...
356,357,Tropius,3,grass,Fruit Pokémon,"['Chlorophyll', 'Solar Power', 'Harvest']",2.0,100.0,99,51,68,83
357,358,Chimecho,3,psychic,Wind Chime Pokémon,['Levitate'],0.6,1.0,75,65,50,80
358,359,Absol,3,dark,Disaster Pokémon,"['Pressure', 'Super Luck', 'Justified']",1.2,47.0,65,115,150,60
359,360,Wynaut,3,psychic,Bright Pokémon,"['Shadow Tag', 'Telepathy']",0.6,14.0,95,23,23,48
360,361,Snorunt,3,ice,Snow Hat Pokémon,"['Inner Focus', 'Ice Body', 'Moody']",0.7,16.8,50,50,50,50
361,362,Glalie,3,ice,Face Pokémon,"['Inner Focus', 'Ice Body', 'Moody']",1.5,256.5,80,100,120,80
362,363,Spheal,3,ice,Clap Pokémon,"['Thick Fat', 'Ice Body', 'Oblivious']",0.8,39.5,70,25,40,50
363,364,Sealeo,3,ice,Ball Roll Pokémon,"['Thick Fat', 'Ice Body', 'Oblivious']",1.1,87.6,90,45,60,70
364,365,Walrein,3,ice,Ice Break Pokémon,"['Thick Fat', 'Ice Body', 'Oblivious']",1.4,150.6,110,65,80,90
365,366,Clamperl,3,water,Bivalve Pokémon,"['Shell Armor', 'Rattled']",0.4,52.5,35,32,64,85
366,367,Huntail,3,water,Deep Sea Pokémon,"['Swift Swim', 'Water Veil']",1.7,27.0,55,52,104,105
367,368,Gorebyss,3,water,South Sea Pokémon,"['Swift Swim', 'Hydration']",1.8,22.6,55,52,84,105
368,369,Relicanth,3,water,Longevity Pokémon,"['Swift Swim', 'Rock Head', 'Sturdy']",1.0,23.4,100,55,90,130
369,370,Luvdisc,3,water,Rendezvous Pokémon,"['Swift Swim', 'Hydration']",0.6,8.7,43,97,30,55
370,371,Bagon,3,dragon,Rock Head Pokémon,"['Rock Head', 'Sheer Force']",0.6,42.1,45,50,75,60
371,372,Shelgon,3,dragon,Endurance Pokémon,"['Rock Head', 'Overcoat']",1.1,110.5,65,50,95,100
372,373,Salamence,3,dragon,Dragon Pokémon,"['Intimidate', 'Moxie']",1.5,102.6,95,120,145,130
373,374,Beldum,3,steel,Iron Ball Pokémon,"['Clear Body', 'Light Metal']",0.6,95.2,40,30,55,80
374,375,Metang,3,steel,Iron Claw Pokémon,"['Clear Body', 'Light Metal']",1.2,202.5,60,50,75,100
375,376,Metagross,3,steel,Iron Leg Pokémon,"['Clear Body', 'Light Metal']",1.6,550.0,80,110,145,150
376,377,Regirock,3,rock,Rock Peak Pokémon,"['Clear Body', 'Sturdy']",1.7,230.0,80,50,100,200
377,378,Regice,3,ice,Iceberg Pokémon,"['Clear Body', 'Ice Body']",1.8,175.0,80,50,50,100
378,379,Registeel,3,steel,Iron Pokémon,"['Clear Body', 'Light Metal']",1.9,205.0,80,50,75,150
379,380,Latias,3,dragon,Eon Pokémon,['Levitate'],1.4,40.0,80,110,100,120
380,381,Latios,3,dragon,Eon Pokémon,['Levitate'],2.0,60.0,80,110,130,100
381,382,Kyogre,3,water,Sea Basin Pokémon,['Drizzle'],4.5,352.0,100,90,150,90
382,383,Groudon,3,ground,Continent Pokémon,['Drought'],3.5,950.0,100,90,180,160
383,384,Rayquaza,3,dragon,Sky High Pokémon,['Air Lock'],7.0,206.5,105,115,180,100
384,385,Jirachi,3,steel,Wish Pokémon,['Serene Grace'],0.3,1.1,100,100,100,100
385,386,Deoxys,3,psychic,DNA Pokémon,['Pressure'],1.7,60.8,50,180,95,90

In [40]:
pokemons[(pokemons.Generation == 3) & (pokemons.Types == 'water')]

,Pokedex Number,Name,Generation,Types,Classfication,Abilities,Height_m,Weight_kg,Hp,Speed,sp_Attack,sp_Defense
257,258,Mudkip,3,water,Mud Fish Pokémon,"['Torrent', 'Damp']",0.4,7.6,50,40,70,50
258,259,Marshtomp,3,water,Mud Fish Pokémon,"['Torrent', 'Damp']",0.7,28.0,70,50,85,70
259,260,Swampert,3,water,Mud Fish Pokémon,"['Torrent', 'Damp']",1.5,81.9,100,70,150,110
269,270,Lotad,3,water,Water Weed Pokémon,"['Swift Swim', 'Rain Dish', 'Own Tempo']",0.5,2.6,40,30,30,30
270,271,Lombre,3,water,Jolly Pokémon,"['Swift Swim', 'Rain Dish', 'Own Tempo']",1.2,32.5,60,50,50,50
271,272,Ludicolo,3,water,Carefree Pokémon,"['Swift Swim', 'Rain Dish', 'Own Tempo']",1.5,55.0,80,70,70,70
277,278,Wingull,3,water,Seagull Pokémon,"['Keen Eye', 'Hydration', 'Rain Dish']",0.6,9.5,40,85,30,30
278,279,Pelipper,3,water,Water Bird Pokémon,"['Keen Eye', 'Drizzle', 'Rain Dish']",1.2,28.0,60,65,50,100
317,318,Carvanha,3,water,Savage Pokémon,"['Rough Skin', 'Speed Boost']",0.8,20.8,45,65,90,20
318,319,Sharpedo,3,water,Brutal Pokémon,"['Rough Skin', 'Speed Boost']",1.8,88.8,70,105,140,70
319,320,Wailmer,3,water,Ball Whale Pokémon,"['Water Veil', 'Oblivious', 'Pressure']",2.0,130.0,130,60,70,35
320,321,Wailord,3,water,Float Whale Pokémon,"['Water Veil', 'Oblivious', 'Pressure']",14.5,398.0,170,60,90,45
338,339,Barboach,3,water,Whiskers Pokémon,"['Oblivious', 'Anticipation', 'Hydration']",0.4,1.9,50,60,48,43
339,340,Whiscash,3,water,Whiskers Pokémon,"['Oblivious', 'Anticipation', 'Hydration']",0.9,23.6,110,60,78,73
340,341,Corphish,3,water,Ruffian Pokémon,"['Hyper Cutter', 'Shell Armor', 'Adaptability']",0.6,11.5,43,35,80,65
341,342,Crawdaunt,3,water,Rogue Pokémon,"['Hyper Cutter', 'Shell Armor', 'Adaptability']",1.1,32.8,63,55,120,85
348,349,Feebas,3,water,Fish Pokémon,"['Swift Swim', 'Oblivious', 'Adaptability']",0.6,7.4,20,80,15,20
349,350,Milotic,3,water,Tender Pokémon,"['Marvel Scale', 'Competitive', 'Cute Charm']",6.2,162.0,95,81,60,79
365,366,Clamperl,3,water,Bivalve Pokémon,"['Shell Armor', 'Rattled']",0.4,52.5,35,32,64,85
366,367,Huntail,3,water,Deep Sea Pokémon,"['Swift Swim', 'Water Veil']",1.7,27.0,55,52,104,105
367,368,Gorebyss,3,water,South Sea Pokémon,"['Swift Swim', 'Hydration']",1.8,22.6,55,52,84,105
368,369,Relicanth,3,water,Longevity Pokémon,"['Swift Swim', 'Rock Head', 'Sturdy']",1.0,23.4,100,55,90,130
369,370,Luvdisc,3,water,Rendezvous Pokémon,"['Swift Swim', 'Hydration']",0.6,8.7,43,97,30,55
381,382,Kyogre,3,water,Sea Basin Pokémon,['Drizzle'],4.5,352.0,100,90,150,90

In [41]:
pokemons[pokemons['Name'] == 'Weedle']

,Pokedex Number,Name,Generation,Types,Classfication,Abilities,Height_m,Weight_kg,Hp,Speed,sp_Attack,sp_Defense
12,13,Weedle,1,bug,Hairy Pokémon,"['Shield Dust', 'Run Away']",0.3,3.2,40,50,35,30

In [42]:
po = float(input('Enter Generation: '))
p = input('Enter Type: ').lower()
pokemons[(pokemons.Generation == po) & (pokemons.Types == p)]

Enter Generation: 1
Enter Type: fire

,Pokedex Number,Name,Generation,Types,Classfication,Abilities,Height_m,Weight_kg,Hp,Speed,sp_Attack,sp_Defense
3,4,Charmander,1,fire,Lizard Pokémon,"['Blaze', 'Solar Power']",0.6,8.5,39,65,52,43
4,5,Charmeleon,1,fire,Flame Pokémon,"['Blaze', 'Solar Power']",1.1,19.0,58,80,64,58
5,6,Charizard,1,fire,Flame Pokémon,"['Blaze', 'Solar Power']",1.7,90.5,78,100,104,78
36,37,Vulpix,1,fire,Fox Pokémon,"['Flash Fire', 'Drought', 'Snow Cloak', 'Snow ...",NaN,NaN,38,65,41,40
37,38,Ninetales,1,fire,Fox Pokémon,"['Flash Fire', 'Drought', 'Snow Cloak', 'Snow ...",NaN,NaN,73,109,67,75
57,58,Growlithe,1,fire,Puppy Pokémon,"['Intimidate', 'Flash Fire', 'Justified']",0.7,19.0,55,60,70,45
58,59,Arcanine,1,fire,Legendary Pokémon,"['Intimidate', 'Flash Fire', 'Justified']",1.9,155.0,90,95,110,80
76,77,Ponyta,1,fire,Fire Horse Pokémon,"['Run Away', 'Flash Fire', 'Flame Body']",1.0,30.0,50,90,85,55
77,78,Rapidash,1,fire,Fire Horse Pokémon,"['Run Away', 'Flash Fire', 'Flame Body']",1.7,95.0,65,105,100,70
125,126,Magmar,1,fire,Spitfire Pokémon,"['Flame Body', 'Vital Spirit']",1.3,44.5,65,93,95,57
135,136,Flareon,1,fire,Flame Pokémon,"['Flash Fire', 'Guts']",0.9,25.0,65,65,130,60
145,146,Moltres,1,fire,Flame Pokémon,"['Pressure', 'Flame Body']",2.0,60.0,90,90,100,90

In [43]:
pok = input("Enter the pokemon's name: ").title()
po = float(input('Enter Generation: '))
p = input('Enter Type: ').lower()

pokemons[(pokemons.Name == pok) & (pokemons.Generation == po) & (pokemons.Types == p)]

Enter the pokemon's name: charmander
Enter Generation: 1
Enter Type: FIRE

,Pokedex Number,Name,Generation,Types,Classfication,Abilities,Height_m,Weight_kg,Hp,Speed,sp_Attack,sp_Defense
3,4,Charmander,1,fire,Lizard Pokémon,"['Blaze', 'Solar Power']",0.6,8.5,39,65,52,43

In [97]:
st = input('Please enter how you want to find your Pokemon (Name, Generation, Type): ').title()

if st == 'Name':
    nam = input("Enter the Pokemon's name : ").title()
    print(intro[intro['Name'] == nam])
elif st == 'Generation':
    gen = float(input('Enter Generation: '))
    print('Here is all the Pokemon is this Generation')
    print(intro[intro['Generation'] == gen])
elif st == 'Type':
    typ = input('Enter Type: ').lower()
    print(intro[intro['Types'] == typ])
else:
    print("Pokemon Can't Determine.")
    
pok = input("Enter the pokemon's name: ").title()
pokemons[pokemons['Name'] == pok]

Please enter how you want to find your Pokemon (Name, Generation, Type): charmander
Pokemon Can't Determine.
Enter the pokemon's name: n

Empty DataFrame
Columns: [Pokedex Number, Name, Generation, Types, Classfication, Abilities, Height_m, Weight_kg, Hp, Speed, sp_Attack, sp_Defense]
Index: []

In [91]:
names = pd.Series(mydata['name'])
generation = pd.Series(mydata['generation'])
types = pd.Series(mydata['type1'])
series_dict = { 'Name':  names, 'Generation': generation, 'Types' : types }  # dict of Series, keys are the series names
intro = pd.DataFrame( series_dict )
intro.sample(2)

           Name  Generation  Types
796  Celesteela           7  steel
267     Cascoon           3    bug

In [18]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [19]:
help(str.translate)

Help on method_descriptor:

translate(...)
    S.translate(table) -> str

    Return a copy of the string S in which each character has been mapped
    through the given translation table. The table must implement
    lookup/indexing via __getitem__, for instance a dictionary or list,
    mapping Unicode ordinals to Unicode ordinals, strings, or None. If
    this operation raises LookupError, the character is left untouched.
    Characters mapped to None are deleted.